vich_uploader:
    db_driver: orm

    mappings:
        invoice_attachment:
            uri_prefix: /attachments/invoice
            upload_destination: '%kernel.project_dir%/public/attachments/invoice'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_origname